version: "3"

services:
  minecraft-fetchr:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: minecraft-fetchr-server
    network_mode: "host"
    # ports:
    #   - "25566:25566"
    restart: unless-stopped
    stop_grace_period: 30s
